### ISSUE TITLE
recursive watch causing some errors

### ISSUE THREAD

**Issue by pzreact** [rjeczalik/notify#110]
Have following log from my go program running on Ubuntu 14.4

goroutine 1 [runnable]:
syscall.Syscall(0xd9, 0x8, 0xc8335b3000, 0x1000, 0xfc0, 0x1000, 0x0)
        /usr/lib/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Getdents(0x8, 0xc8335b3000, 0x1000, 0x1000, 0xc8335b3f73, 0x0, 0x0)
        /usr/lib/go/src/syscall/zsyscall_linux_amd64.go:508 +0x5f
syscall.ReadDirent(0x8, 0xc8335b3000, 0x1000, 0x1000, 0xc834aca000, 0x0, 0x0)
        /usr/lib/go/src/syscall/syscall_linux.go:771 +0x4d
os.(*File).readdirnames(0xc820030080, 0xffffffffffff5acf, 0xc834aca000, 0xa530, 0xbc00, 0x0, 0x0)
        /usr/lib/go/src/os/dir_unix.go:39 +0x215
os.(*File).Readdirnames(0xc820030080, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/os/doc.go:138 +0x85
os.(*File).readdir(0xc820030080, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/os/file_unix.go:196 +0xb3
os.(*File).Readdir(0xc820030080, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/os/doc.go:119 +0x85
io/ioutil.ReadDir(0xc820196c80, 0x36, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/io/ioutil/ioutil.go:105 +0xcc
github.com/rjeczalik/notify.node.AddDir(0xc820196c80, 0x36, 0xc820152cf0, 0xc820152d20, 0xc82000e4c0, 0x0, 0x0)
        /home/deploy/code/pzproxy-go/src/github.com/rjeczalik/notify/node.go:78 +0x1f2
github.com/rjeczalik/notify.(node).AddDir-fm(0xc82000e4c0, 0x0, 0x0)
        /home/deploy/code/pzproxy-go/src/github.com/rjeczalik/notify/tree_nonrecursive.go:222 +0x42
github.com/rjeczalik/notify.(*nonrecursiveTree).watchrec(0xc8200721e0, 0x5d1860, 0x15, 0xc82000a810, 0xc82000a840, 0xc820072360, 0x1300000, 0x0, 0x0)
        /home/deploy/code/pzproxy-go/src/github.com/rjeczalik/notify/tree_nonrecursive.go:228 +0x424
github.com/rjeczalik/notify.(*nonrecursiveTree).Watch(0xc8200721e0, 0x5d1860, 0x15, 0xc820072360, 0xc8200108f0, 0x2, 0x2, 0x0, 0x0)
        /home/deploy/code/pzproxy-go/src/github.com/rjeczalik/notify/tree_nonrecursive.go:165 +0x288
github.com/rjeczalik/notify.Watch(0x5d1860, 0x19, 0xc820072360, 0xc8200108f0, 0x2, 0x2, 0x0, 0x0)
        /home/deploy/code/pzproxy-go/src/github.com/rjeczalik/notify/notify.go:64 +0x7d

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [chan receive]:
github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc8200721e0, 0xc820072120)
        /home/deploy/code/pzproxy-go/src/github.com/rjeczalik/notify/tree_nonrecursive.go:36 +0x5c
created by github.com/rjeczalik/notify.newNonrecursiveTree
        /home/deploy/code/pzproxy-go/src/github.com/rjeczalik/notify/tree_nonrecursive.go:29 +0x21e

goroutine 6 [chan receive]:
github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc8200721e0, 0xc820072180)
        /home/deploy/code/pzproxy-go/src/github.com/rjeczalik/notify/tree_nonrecursive.go:81 +0x7b
created by github.com/rjeczalik/notify.newNonrecursiveTree
        /home/deploy/code/pzproxy-go/src/github.com/rjeczalik/notify/tree_nonrecursive.go:30 +0x24d

goroutine 656 [semacquire]:
sync.runtime_Semacquire(0xc8200721ec)
        /usr/lib/go/src/runtime/sema.go:47 +0x26
sync.(*RWMutex).RLock(0xc8200721e0)
        /usr/lib/go/src/sync/rwmutex.go:37 +0x58
github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch.func1(0xc8200721e0, 0x7fd31c122b10, 0xc8223b8a20)
        /home/deploy/code/pzproxy-go/src/github.com/rjeczalik/notify/tree_nonrecursive.go:51 +0x146
created by github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch
        /home/deploy/code/pzproxy-go/src/github.com/rjeczalik/notify/tree_nonrecursive.go:75 +0x20c

goroutine 770 [semacquire]:
sync.runtime_Semacquire(0xc8200721ec)
        /usr/lib/go/src/runtime/sema.go:47 +0x26
sync.(*RWMutex).RLock(0xc8200721e0)
        /usr/lib/go/src/sync/rwmutex.go:37 +0x58
github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch.func1(0xc8200721e0, 0x7fd31c122b10, 0xc8223b8a50)
        /home/deploy/code/pzproxy-go/src/github.com/rjeczalik/notify/tree_nonrecursive.go:51 +0x146
created by github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch
        /home/deploy/code/pzproxy-go/src/github.com/rjeczalik/notify/tree_nonrecursive.go:75 +0x20c

goroutine 771 [semacquire]:
sync.runtime_Semacquire(0xc8200721ec)
        /usr/lib/go/src/runtime/sema.go:47 +0x26
sync.(*RWMutex).RLock(0xc8200721e0)
        /usr/lib/go/src/sync/rwmutex.go:37 +0x58
github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch.func1(0xc8200721e0, 0x7fd31c122b10, 0xc8223b8a80)
        /home/deploy/code/pzproxy-go/src/github.com/rjeczalik/notify/tree_nonrecursive.go:51 +0x146
created by github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch
        /home/deploy/code/pzproxy-go/src/github.com/rjeczalik/notify/tree_nonrecursive.go:75 +0x20c

**Comment by rjeczalik** [comment]
@pzreact Is it a panic? What does it say? Where are the sources for your go program?

**Comment by pzreact** [comment]
I see it happens only when I run program under supervisord. When I run manually everything is fine, 
not sure what causing the difference.

**Comment by rjeczalik** [comment]
@pzreact Where are the sources for your go program?
