### ISSUE TITLE
kqueue: failed to read events: "interrupted system call"

### ISSUE THREAD

**Issue by rjeczalik** [rjeczalik/notify#49]
Just FYI @pblaszczyk, probably it's just broken for OS X.

Steps to reproduce (sorry, no test yet).

```
~ $ go install github.com/rjeczalik/fs/cmd/mktree github.com/rjeczalik/fs/cmd/gotree
~ $ go install github.com/rjeczalik/notify/cmd/notify
~ $ # run in different terminal: notify $HOME/...
~ $ mkdir -p /tmp/1/2/3
~ $ touch /tmp/1/2.txt                                                                                                                            
~ $ touch /tmp/1/2/3.txt                                                                                                                          
~ $ touch /tmp/1/2/3/.txt
~ $ gotree /tmp/1 | mktree -o .
```

Panics with:

```
panic: permission denied

goroutine 20 [running]:
runtime.panic(0xe20a0, 0xd)
        /usr/local/gvm/gos/go1.3.3/src/pkg/runtime/panic.c:279 +0xf5
github.com/rjeczalik/notify.func·009(0x22081e94f0, 0x20824bd60, 0x0, 0x0)
        /Users/rjeczalik/Workspace/src/github.com/rjeczalik/notify/watcher_kqueue.go:143 +0x244
github.com/rjeczalik/notify.(*kqueue).walk(0x2081fc330, 0x208216100, 0x3a, 0x22083a0f28, 0x0, 0x0)
        /Users/rjeczalik/Workspace/src/github.com/rjeczalik/notify/watcher_kqueue.go:299 +0x155
github.com/rjeczalik/notify.(*kqueue).monitor(0x2081fc330)
        /Users/rjeczalik/Workspace/src/github.com/rjeczalik/notify/watcher_kqueue.go:149 +0x911
created by github.com/rjeczalik/notify.(*kqueue).Dispatch
        /Users/rjeczalik/Workspace/src/github.com/rjeczalik/notify/watcher_kqueue.go:376 +0x41

goroutine 16 [chan receive]:
main.main()
        /Users/rjeczalik/Workspace/src/github.com/rjeczalik/notify/cmd/notify/main.go:49 +0x1b0

goroutine 19 [finalizer wait, 1 minutes]:
runtime.park(0x14ef0, 0x19b810, 0x19ab89)
        /usr/local/gvm/gos/go1.3.3/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x19b810, 0x19ab89)
        /usr/local/gvm/gos/go1.3.3/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/local/gvm/gos/go1.3.3/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/local/gvm/gos/go1.3.3/src/pkg/runtime/proc.c:1445

goroutine 21 [select, 1 minutes]:
github.com/rjeczalik/notify.(*Tree).loopdispatch(0x2081f2280, 0x2081eb200)
        /Users/rjeczalik/Workspace/src/github.com/rjeczalik/notify/tree.go:179 +0x478
created by github.com/rjeczalik/notify.NewTree
        /Users/rjeczalik/Workspace/src/github.com/rjeczalik/notify/tree.go:217 +0x1c6
```

**Comment by rjeczalik** [comment]
fd8811f3668f7d1b7

**Comment by rjeczalik** [comment]
https://travis-ci.org/rjeczalik/notify/builds/47973996

@pblaszczyk Good job sir! Want a kudo? XD
